//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mupl
{
    using System;
    using System.Collections.Generic;
    using System.Drawing;
    using System.IO;

    public partial class label
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public label()
        {
            this.performer = new HashSet<performer>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public string photo { get; set; }
        public string picture
        {
            get
            {
                string path = $"{Directory.GetCurrentDirectory()}\\Images\\{photo}";
                if (File.Exists(path))
                    return path;

                return $"{Directory.GetCurrentDirectory()}\\Images\\photo0.png";
            }
            set { }
        }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<performer> performer { get; set; }
    }
}
