//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mupl
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class muplEntities : DbContext
    {
        
        public muplEntities()
            : base("name=muplEntities")
        {
        }

        private static muplEntities _context;
        public static muplEntities GetContext()
        {
            if (_context == null)
                _context = new muplEntities();
            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<album> album { get; set; }
        public virtual DbSet<genre> genre { get; set; }
        public virtual DbSet<label> label { get; set; }
        public virtual DbSet<performer> performer { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<track> track { get; set; }
        public virtual DbSet<track_genre> track_genre { get; set; }
        public virtual DbSet<user_track> user_track { get; set; }
        public virtual DbSet<users> users { get; set; }
    }
}
