//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mupl
{
    using System;
    using System.Collections.Generic;
    using System.IO;

    public partial class users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public users()
        {
            this.user_track = new HashSet<user_track>();
        }
    
        public int id { get; set; }
        public string login { get; set; }
        public string password { get; set; }
        public string role { get; set; }
        public string photo { get; set; }
        public string picture
        {
            get
            {
                string path = $"{Directory.GetCurrentDirectory()}\\Images\\{photo}";
                if (File.Exists(path))
                    return path;

                return $"{Directory.GetCurrentDirectory()}\\Images\\photo0.png";
            }
            set { }
        }
        public string email { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<user_track> user_track { get; set; }
    }
}
